# Generated by Django 5.0.3 on 2024-03-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0003_customuser2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser2',
        ),
    ]
