# Generated by Django 5.0.3 on 2024-03-25 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_Accounts', '0002_alter_customuser_password_alter_customuser_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='User_Dashboard.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('definition_explanation', models.TextField()),
                ('real_world_example', models.TextField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='User_Dashboard.keyconcept')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='User_Dashboard.module'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('concept_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='User_Dashboard.conceptdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='User_Dashboard.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='UserChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Dashboard.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Accounts.customuser')),
            ],
            options={
                'unique_together': {('user', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='UserConceptProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Dashboard.keyconcept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Accounts.customuser')),
            ],
            options={
                'unique_together': {('user', 'concept')},
            },
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Dashboard.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Accounts.customuser')),
            ],
            options={
                'unique_together': {('user', 'module')},
            },
        ),
    ]
