# Generated by Django 5.0.3 on 2024-03-25 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='concept_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='User_Dashboard.keyconcept'),
        ),
    ]
