# Generated by Django 5.0.3 on 2024-03-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Dashboard', '0003_alter_keyconcept_title_achievementtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyconcept',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
