# Generated by Django 5.0.3 on 2024-04-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Dashboard', '0006_usercurrentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercurrentprogress',
            name='current_quiz_no',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='achievementtracker',
            name='badge',
            field=models.CharField(blank=True, default='Beginner', help_text='The highest badge the user has earned.', max_length=100, null=True),
        ),
    ]
