# Generated by Django 5.0.3 on 2024-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Dashboard', '0007_usercurrentprogress_current_quiz_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercurrentprogress',
            name='current_quiz_no',
            field=models.IntegerField(default=1),
        ),
    ]
