# Generated by Django 5.0.3 on 2024-04-15 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Dashboard', '0008_alter_usercurrentprogress_current_quiz_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_no', models.IntegerField(choices=[(1, 'Module 1'), (2, 'Module 2'), (3, 'Module 3'), (4, 'Module 4'), (5, 'Module 5'), (6, 'Module 6'), (7, 'Module 7'), (8, 'Module 8')])),
                ('chapter_no', models.IntegerField(choices=[(1, 'Chapter 1'), (2, 'Chapter 2'), (3, 'Chapter 3'), (4, 'Chapter 4'), (5, 'Chapter 5')])),
                ('concept_no', models.IntegerField(choices=[(1, 'Concept 1'), (3, 'Concept 3')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
